version: '3.8'
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: notedb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
